services:
  hrm-core:
    build:
      context: hrm-core
    restart: unless-stopped
    volumes:
      - '.:/usr/src/app'
    ports:
      - "5000:5000"
    environment:
      ENVIRONMENT: local
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: hrm_core
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - minio_data:/data
      - minio_data:/root/.minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"

volumes:
  postgresql_data:
  minio_data:
