version: '3'

services:
  {{ cookiecutter.project_name }}:
    build: 
      context: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - "5000:5000"
    environment:
      ENVIRONMENT: local

{% if cookiecutter.use_postgresql|lower == 'y' -%}
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: zasxcdfv
      POSTGRES_USER: {{ cookiecutter.project_slug }}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
{%- endif %}
