[project]
name = "fastapi-app"
version = "1.0.0"
description = "fvd ervsfd"
authors = [
    { name = "dfwv ergs", email = "author@mail.dev" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "granian[reload,pname]",
    "pydantic[email]",
    "pydantic-settings",
    "pyjwt[crypto]",
    "asyncpg",
    "sqlalchemy[asyncio]",
    "alembic",
    "python-json-logger",
    "sentry-sdk[fastapi,opentelemetry-otlp]",
    "prometheus-fastapi-instrumentator",
    "redis[hiredis]",
    "aiokafka[lz4,zstd]",
    "nats-py",
    "nats-jetstream",
    "httpx[http2]",
#    "taskiq",
    "opentelemetry-distro",
#    "opentelemetry-exporter-otlp",  # enable only if you plan to send traces somewhere other than Sentry
    "opentelemetry-instrumentation-fastapi",
    "opentelemetry-instrumentation-sqlalchemy",
    "opentelemetry-instrumentation-httpx",
    "opentelemetry-instrumentation-redis",
    "opentelemetry-instrumentation-aiokafka",
    ]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "pytest-mock",
    "pytest-xdist",
    "pytest-cov",
    "pre-commit",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.14"
disable_error_code = "import-untyped"

[tool.ruff]
src = ["src"]
target-version = "py314"
line-length = 120
fix = true
#unsafe-fixes = true
show-fixes = true
output-format = "grouped"

[tool.ruff.lint]
select = [
    "E", "W", "F", "I", "B", "C4", "ANN", "SIM",
    "T10", # flake8-debugger
    "T20", # flake8-print
    "S", # flake8-bandit
    "C90", # mccabe
    "TCH", # flake8-type-checking
    "UP", "FA", "FAST", "ASYNC", "PERF", "RUF", "PT",
    "A",   # flake8-builtins
    "BLE", # flake8-blind-except
    "PTH", # flake8-use-pathlib
    "RET", # flake8-return
    "D",   # pydocstyle
]
ignore = [
    "D203", # one blank line before class, handled by pydocstyle
    "D212", # may conflict with D213 when using Google convention
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ANN", "S101", "D"]
"src/infrastructure/clients/postgres/migrations/*" = ["ANN", "D"]
"src/infrastructure/clients/postgres/models/items.py" = ["TCH"]
"src/infrastructure/core/settings.py" = ["TCH"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]
runtime-evaluated-base-classes = ["pydantic.BaseModel", "sqlalchemy.orm.DeclarativeBase"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "fastapi.Path", "pydantic.Field"]

[tool.ruff.lint.flake8-bandit]
check-typed-exception = true
hardcoded-tmp-directory = ["/tmp", "/var/tmp", "/dev/shm"]

[tool.ruff.lint.isort]
combine-as-imports = true
order-by-type = true
force-sort-within-sections = true
# split-on-trailing-comma = false
known-first-party = ["src"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
skip-magic-trailing-comma = true
docstring-code-format = true
docstring-code-line-length = 80

[tool.pytest.ini_options]
minversion = "9.0"
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]
omit = ["tests/*"]
data_file = "tests/coverage/.coverage"

[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "logger.",
    "def build_spec.*:",
    "except ConnectionRefusedError",
]
