[project]
name = "{{ cookiecutter.project_name }}"
version = "{{ cookiecutter.project_release }}"
description = "{{ cookiecutter.project_description }}"
authors = [{ name = "{{ cookiecutter.app_developer }}", email = "author@mail.dev" }]
readme = "README.md"
requires-python = ">={{ cookiecutter.app_lang_version }},<4"
dependencies = [
    "fastapi",
    "granian[reload,pname]",
    "pydantic[email]",
    "pydantic-settings",
    {% if cookiecutter.use_jwt|lower == 'y' -%}
    "pyjwt[crypto]",
    {% endif -%}
    {% if cookiecutter.use_postgresql|lower == 'y' or cookiecutter.use_alembic|lower == 'y' -%}
    "asyncpg",
    {% endif -%}
    {% if cookiecutter.use_postgresql|lower == 'y' -%}
    "sqlalchemy[asyncio]",
    {% endif -%}
    {% if cookiecutter.use_alembic|lower == 'y' -%}
    "alembic",
    {% endif -%}
    "python-json-logger",
    "sentry-sdk[fastapi,opentelemetry-otlp]",
    "prometheus-fastapi-instrumentator",
    {% if cookiecutter.use_redis|lower == 'y' -%}
    "redis[hiredis]",
    {% endif -%}
    {% if cookiecutter.use_kafka|lower == 'y' -%}
    "aiokafka[lz4,zstd]",
    {% endif -%}
    {% if cookiecutter.use_nats|lower == 'y' -%}
    "nats-py",
    "nats-jetstream",
    {% endif -%}
    "httpx2[http2]",
    {% if cookiecutter.use_background_tasks|lower == 'y' -%}
    "taskiq",
    {% endif -%}
    "opentelemetry-distro",
    "opentelemetry-instrumentation-logging",
    "opentelemetry-instrumentation-fastapi",
    {% if cookiecutter.use_postgresql|lower == 'y' -%}
    "opentelemetry-instrumentation-sqlalchemy",
    {% endif -%}
    "opentelemetry-instrumentation-httpx",
    {% if cookiecutter.use_redis|lower == 'y' -%}
    "opentelemetry-instrumentation-redis",
    {% endif -%}
    {% if cookiecutter.use_kafka|lower == 'y' -%}
    "opentelemetry-instrumentation-aiokafka",
    {% endif -%}
    #    "opentelemetry-exporter-otlp",  # enable only if you plan to send traces somewhere other than Sentry
    ]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "pytest-mock",
    "pytest-xdist",
    "pytest-cov",
    "pre-commit",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "{{ cookiecutter.app_lang_version }}"
disable_error_code = "import-untyped"

[tool.ruff]
src = ["src"]
target-version = "py{{ cookiecutter.app_lang_version|replace('.', '') }}"
line-length = 120
fix = true
#unsafe-fixes = true
show-fixes = true
output-format = "grouped"

[tool.ruff.lint]
select = [
    "E", "W", "F", "I", "B", "C4", "ANN", "SIM",
    "T10", # flake8-debugger
    "T20", # flake8-print
    "S", # flake8-bandit
    "C90", # mccabe
    "TCH", # flake8-type-checking
    "UP", "FA", "FAST", "ASYNC", "PERF", "RUF", "PT",
    "A",   # flake8-builtins
    "BLE", # flake8-blind-except
    "PTH", # flake8-use-pathlib
    "RET", # flake8-return
    "D",   # pydocstyle
    "DTZ", # flake8-datetimez
    "N",   # pep8-naming
    "TRY", # tryceratops
    "PLC", "PLE", "PLW", #"PLR", # Pylint
    "PIE", # flake8-pie
    "ISC", # flake8-implicit-str-concat
    "FBT", # flake8-boolean-trap
    "ARG", # flake8-unused-arguments
    "ERA", # eradicate
]
ignore = [
    "D203", # one blank line before class, handled by pydocstyle
    "D212", # may conflict with D213 when using Google convention
    "ANN401",
    "TRY003",
    "PLW2901",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ANN", "S101", "D", "PLR2004", "ARG", "FBT"]
"src/infrastructure/clients/postgres/migrations/*" = ["ANN", "D", "INP"]
"src/infrastructure/clients/postgres/models/items.py" = ["TCH"]
"src/infrastructure/core/settings.py" = ["TCH"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]
runtime-evaluated-base-classes = ["pydantic.BaseModel", "sqlalchemy.orm.DeclarativeBase"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "fastapi.Path", "pydantic.Field"]

[tool.ruff.lint.flake8-bandit]
check-typed-exception = true
hardcoded-tmp-directory = ["/tmp", "/var/tmp", "/dev/shm"]

[tool.ruff.lint.isort]
combine-as-imports = true
order-by-type = true
force-sort-within-sections = true
# split-on-trailing-comma = false
known-first-party = ["src"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
skip-magic-trailing-comma = true
docstring-code-format = true
docstring-code-line-length = 80

[tool.pytest.ini_options]
minversion = "9.0"
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]
omit = ["tests/*"]
data_file = "tests/coverage/.coverage"

[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "logger.",
    "def build_spec.*:",
    "except ConnectionRefusedError",
]
