"""change Item.price to numeric

Revision ID: 2aa3e57d0fe6
Revises: 05cf2ca8a9f9
Create Date: 2026-02-28 16:02:59.025818

"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op
import sqlalchemy as sa

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2aa3e57d0fe6"
down_revision: str | Sequence[str] | None = "05cf2ca8a9f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "items", "name", existing_type=sa.VARCHAR(length=200), type_=sa.String(length=256), existing_nullable=False
    )
    op.alter_column(
        "items", "price", existing_type=sa.INTEGER(), type_=sa.Numeric(precision=16, scale=8), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "items", "price", existing_type=sa.Numeric(precision=16, scale=8), type_=sa.INTEGER(), existing_nullable=False
    )
    op.alter_column(
        "items", "name", existing_type=sa.String(length=256), type_=sa.VARCHAR(length=200), existing_nullable=False
    )
    # ### end Alembic commands ###
